# Generated by Django 3.1.8 on 2021-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroes',
            name='alter_ego',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='catch_phrase',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='primary_power',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='secondary_power',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
