# Generated by Django 3.1.8 on 2021-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperHeroes', '0002_auto_20210505_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
